### PR TITLE
Enhancing User Experience and Adding New Features to Portfolio Website"

### PR DESCRIPTION
**Pull request by umarahgul**
Revamping the website's overall design to create a visually appealing and modern look.

### CODE REVIEW

**Review by Tufahel — CHANGES_REQUESTED** [review]
Hi @umarahgul, 👋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 

## Invalid Code Review Request

You have submitted a project, but you haven't added the [professional readme](https://github.com/microverseinc/readme-template) given by microverse.

- [ ] Kindly add the readme and customize the details and other things as per your project requirements.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by shella12 — COMMENTED** [review]
Hi @umarahgul, 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [ ] Doesn't have professional README. Make sure to use `markups` to make your README look like the template and not one big jumbled script as it's really hard to read.
- [ ] Has linter errors please fix the stylelint errors 
- [ ] Doesn't have good branch name. Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section') . `feature1` is not a descriptive name.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by umarahgul** [comment]
@shella12 I am unable rename the branch . If i update from shell, I am unable to push to the newly named branch and when I rename from repo it informs me that the pull request would be closed for this branch. please help.

**Review by shahadat3669 — CHANGES_REQUESTED** [review]
Hi @umarahgul , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

You have submitted a project, that has an invalid branch name, PR description, and Readme file.
- You have submitted a project, that has an invalid readme file. Please take your time and update it according to the [template](https://github.com/microverseinc/readme-template). If you use "VS Code" you can follow this [article ](https://code.visualstudio.com/docs/languages/markdown#:~:text=You%20can%20view%20the%20preview,real%2Dtime%20as%20you%20edit.)to update your readme file.

| Your | Professional |
| --- | --- |
| image | image |

-The branch name you have chosen does not provide a clear indication of the feature or action being implemented. It is important to use descriptive branch names that accurately describe the purpose of the branch. For example, instead of a generic name like "feature1," consider using names like "**created\_sidebar**" or "**added\_comments\_section**" that convey the specific feature or action being worked on. :pray: Please rename the branch to a meaningful name. Check out this [official document](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) for further help. :+1:
-The pull request description should be descriptive and provide context about the changes being introduced. Take the opportunity to explain the purpose, implementation details, and any relevant information that would help reviewers understand the changes better. :+1: Please change the PR description which describes what you did in this PR.

| Your | Professional |
| --- | --- |
| image | image |

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
